.align 4

Item620:
	Price 1794
	HeldEffect 1
	HeldArgument 120
	NaturalGiftEffect 100
	FlingEffect 5
	FlingPower 0
	NaturalGiftPower 0
	Packed 0
	FieldEffect 0
	BattleEffect 0
	HasBattleStats 0
	ItemClass 0
	Consumable 0
	SortIndex 0
Item620_BattleStats:
	CureInflict 229
	Boost 0, 0, 0, 0
	FunctionFlags0 2
	FunctionFlags1 4
	EVHP 0
	EVATK 255
	EVDEF 255
	EVSPE 0
	EVSPA 100
	EVSPD 100
	HealAmount 0
	PPGain 83
	Friendship1 83
	Friendship2 73
	Friendship3 8
	Unk1F 0
	Unk20 0
