.align 4

Item364:
	Price 0
	HeldEffect 1
	HeldArgument 30
	NaturalGiftEffect 100
	FlingEffect 10
	FlingPower 2
	NaturalGiftPower 0
	Packed 0
	FieldEffect 0
	BattleEffect 0
	HasBattleStats 0
	ItemClass 0
	Consumable 0
	SortIndex 0
Item364_BattleStats:
	CureInflict 223
	Boost 0, 0, 0, 0
	FunctionFlags0 0
	FunctionFlags1 0
	EVHP 0
	EVATK 0
	EVDEF 0
	EVSPE 0
	EVSPA 0
	EVSPD 0
	HealAmount 0
	PPGain 83
	Friendship1 83
	Friendship2 64
	Friendship3 0
	Unk1F 0
	Unk20 0
