.align 4

Item599:
	Price 515
	HeldEffect 0
	HeldArgument 0
	NaturalGiftEffect 100
	FlingEffect 20
	FlingPower 0
	NaturalGiftPower 0
	Packed 0
	FieldEffect 0
	BattleEffect 0
	HasBattleStats 0
	ItemClass 0
	Consumable 0
	SortIndex 0
Item599_BattleStats:
	CureInflict 107
	Boost 1, 0, 0, 5
	FunctionFlags0 1
	FunctionFlags1 3
	EVHP 5
	EVATK 255
	EVDEF 255
	EVSPE 255
	EVSPA 100
	EVSPD 100
	HealAmount 100
	PPGain 83
	Friendship1 83
	Friendship2 88
	Friendship3 0
	Unk1F 0
	Unk20 0
