.align 4

Item122:
	Price 1031
	HeldEffect 1
	HeldArgument 30
	NaturalGiftEffect 100
	FlingEffect 30
	FlingPower 0
	NaturalGiftPower 0
	Packed 1
	FieldEffect 30
	BattleEffect 1
	HasBattleStats 0
	ItemClass 0
	Consumable 0
	SortIndex 0
Item122_BattleStats:
	CureInflict 6
	Boost 0, 0, 0, 0
	FunctionFlags0 0
	FunctionFlags1 0
	EVHP 0
	EVATK 0
	EVDEF 0
	EVSPE 0
	EVSPA 0
	EVSPD 0
	HealAmount 0
	PPGain 83
	Friendship1 83
	Friendship2 73
	Friendship3 0
	Unk1F 0
	Unk20 0
