.align 4

Item602:
	Price 524
	HeldEffect 0
	HeldArgument 0
	NaturalGiftEffect 101
	FlingEffect 20
	FlingPower 0
	NaturalGiftPower 0
	Packed 0
	FieldEffect 0
	BattleEffect 0
	HasBattleStats 0
	ItemClass 0
	Consumable 0
	SortIndex 0
Item602_BattleStats:
	CureInflict 110
	Boost 1, 0, 0, 6
	FunctionFlags0 2
	FunctionFlags1 4
	EVHP 0
	EVATK 1
	EVDEF 1
	EVSPE 0
	EVSPA 0
	EVSPD 0
	HealAmount 0
	PPGain 83
	Friendship1 83
	Friendship2 32
	Friendship3 40
	Unk1F 0
	Unk20 0
