.align 4

Item231:
	Price 1544
	HeldEffect 1
	HeldArgument 100
	NaturalGiftEffect 75
	FlingEffect 15
	FlingPower 0
	NaturalGiftPower 0
	Packed 0
	FieldEffect 0
	BattleEffect 0
	HasBattleStats 0
	ItemClass 0
	Consumable 0
	SortIndex 0
Item231_BattleStats:
	CureInflict 69
	Boost 0, 0, 0, 0
	FunctionFlags0 2
	FunctionFlags1 0
	EVHP 0
	EVATK 255
	EVDEF 0
	EVSPE 0
	EVSPA 30
	EVSPD 0
	HealAmount 0
	PPGain 83
	Friendship1 83
	Friendship2 73
	Friendship3 0
	Unk1F 0
	Unk20 0
