.align 4

Item257:
	Price 1033
	HeldEffect 2
	HeldArgument 95
	NaturalGiftEffect 90
	FlingEffect 10
	FlingPower 0
	NaturalGiftPower 0
	Packed 4
	FieldEffect 10
	BattleEffect 1
	HasBattleStats 0
	ItemClass 0
	Consumable 0
	SortIndex 0
Item257_BattleStats:
	CureInflict 4
	Boost 0, 0, 0, 5
	FunctionFlags0 0
	FunctionFlags1 0
	EVHP 0
	EVATK 0
	EVDEF 0
	EVSPE 0
	EVSPA 0
	EVSPD 0
	HealAmount 0
	PPGain 83
	Friendship1 83
	Friendship2 72
	Friendship3 0
	Unk1F 0
	Unk20 0
