.align 4

Item466:
	Price 1799
	HeldEffect 2
	HeldArgument 60
	NaturalGiftEffect 100
	FlingEffect 5
	FlingPower 0
	NaturalGiftPower 0
	Packed 0
	FieldEffect 10
	BattleEffect 0
	HasBattleStats 0
	ItemClass 0
	Consumable 0
	SortIndex 0
Item466_BattleStats:
	CureInflict 140
	Boost 0, 0, 0, 0
	FunctionFlags0 8
	FunctionFlags1 0
	EVHP 0
	EVATK 1
	EVDEF 0
	EVSPE 0
	EVSPA 10
	EVSPD 0
	HealAmount 0
	PPGain 83
	Friendship1 83
	Friendship2 72
	Friendship3 0
	Unk1F 0
	Unk20 0
