.align 4

Item154:
	Price 0
	HeldEffect 1
	HeldArgument 18
	NaturalGiftEffect 80
	FlingEffect 15
	FlingPower 0
	NaturalGiftPower 82
	Packed 0
	FieldEffect 0
	BattleEffect 0
	HasBattleStats 0
	ItemClass 0
	Consumable 0
	SortIndex 0
Item154_BattleStats:
	CureInflict 29
	Boost 0, 0, 0, 0
	FunctionFlags0 0
	FunctionFlags1 0
	EVHP 0
	EVATK 0
	EVDEF 0
	EVSPE 0
	EVSPA 0
	EVSPD 0
	HealAmount 0
	PPGain 83
	Friendship1 83
	Friendship2 73
	Friendship3 128
	Unk1F 0
	Unk20 0
