.align 4

Item508:
	Price 520
	HeldEffect 0
	HeldArgument 0
	NaturalGiftEffect 101
	FlingEffect 10
	FlingPower 0
	NaturalGiftPower 0
	Packed 0
	FieldEffect 0
	BattleEffect 0
	HasBattleStats 0
	ItemClass 0
	Consumable 0
	SortIndex 0
Item508_BattleStats:
	CureInflict 56
	Boost 1, 0, 0, 7
	FunctionFlags0 5
	FunctionFlags1 1
	EVHP 0
	EVATK 2
	EVDEF 1
	EVSPE 0
	EVSPA 0
	EVSPD 0
	HealAmount 0
	PPGain 83
	Friendship1 83
	Friendship2 32
	Friendship3 0
	Unk1F 0
	Unk20 0
