.align 4

Item557:
	Price 1801
	HeldEffect 1
	HeldArgument 180
	NaturalGiftEffect 95
	FlingEffect 5
	FlingPower 0
	NaturalGiftPower 0
	Packed 0
	FieldEffect 0
	BattleEffect 0
	HasBattleStats 0
	ItemClass 0
	Consumable 0
	SortIndex 0
Item557_BattleStats:
	CureInflict 78
	Boost 1, 0, 0, 0
	FunctionFlags0 5
	FunctionFlags1 2
	EVHP 4
	EVATK 255
	EVDEF 255
	EVSPE 255
	EVSPA 100
	EVSPD 100
	HealAmount 100
	PPGain 83
	Friendship1 83
	Friendship2 73
	Friendship3 0
	Unk1F 0
	Unk20 0
