.align 4

Item264:
	Price 1
	HeldEffect 1
	HeldArgument 150
	NaturalGiftEffect 100
	FlingEffect 20
	FlingPower 253
	NaturalGiftPower 0
	Packed 0
	FieldEffect 0
	BattleEffect 0
	HasBattleStats 0
	ItemClass 0
	Consumable 0
	SortIndex 0
Item264_BattleStats:
	CureInflict 170
	Boost 0, 0, 0, 0
	FunctionFlags0 0
	FunctionFlags1 0
	EVHP 0
	EVATK 0
	EVDEF 0
	EVSPE 0
	EVSPA 0
	EVSPD 0
	HealAmount 0
	PPGain 83
	Friendship1 83
	Friendship2 137
	Friendship3 0
	Unk1F 0
	Unk20 0
