.align 4

Item260:
	Price 1296
	HeldEffect 0
	HeldArgument 0
	NaturalGiftEffect 100
	FlingEffect 15
	FlingPower 0
	NaturalGiftPower 0
	Packed 6
	FieldEffect 0
	BattleEffect 2
	HasBattleStats 2
	ItemClass 5
	Consumable 0
	SortIndex 0
Item260_BattleStats:
	CureInflict 166
	Boost 0, 0, 0, 0
	FunctionFlags0 3
	FunctionFlags1 0
	EVHP 0
	EVATK 1
	EVDEF 0
	EVSPE 0
	EVSPA 0
	EVSPD 0
	HealAmount 0
	PPGain 83
	Friendship1 83
	Friendship2 88
	Friendship3 128
	Unk1F 0
	Unk20 0
