.align 4

Item373:
	Price 272
	HeldEffect 0
	HeldArgument 0
	NaturalGiftEffect 100
	FlingEffect 15
	FlingPower 0
	NaturalGiftPower 0
	Packed 19
	FieldEffect 0
	BattleEffect 2
	HasBattleStats 5
	ItemClass 5
	Consumable 0
	SortIndex 0
Item373_BattleStats:
	CureInflict 232
	Boost 0, 0, 0, 0
	FunctionFlags0 0
	FunctionFlags1 0
	EVHP 0
	EVATK 0
	EVDEF 0
	EVSPE 0
	EVSPA 0
	EVSPD 0
	HealAmount 0
	PPGain 83
	Friendship1 83
	Friendship2 88
	Friendship3 0
	Unk1F 0
	Unk20 0
