.align 4

Item547:
	Price 1024
	HeldEffect 2
	HeldArgument 75
	NaturalGiftEffect 100
	FlingEffect 10
	FlingPower 0
	NaturalGiftPower 0
	Packed 2
	FieldEffect 10
	BattleEffect 2
	HasBattleStats 2
	ItemClass 4
	Consumable 0
	SortIndex 0
Item547_BattleStats:
	CureInflict 73
	Boost 1, 0, 0, 5
	FunctionFlags0 0
	FunctionFlags1 0
	EVHP 0
	EVATK 0
	EVDEF 0
	EVSPE 0
	EVSPA 0
	EVSPD 0
	HealAmount 0
	PPGain 83
	Friendship1 83
	Friendship2 72
	Friendship3 33
	Unk1F 0
	Unk20 0
