.align 4

Item621:
	Price 1808
	HeldEffect 1
	HeldArgument 100
	NaturalGiftEffect 101
	FlingEffect 5
	FlingPower 0
	NaturalGiftPower 0
	Packed 0
	FieldEffect 0
	BattleEffect 0
	HasBattleStats 0
	ItemClass 0
	Consumable 0
	SortIndex 0
Item621_BattleStats:
	CureInflict 103
	Boost 1, 0, 0, 0
	FunctionFlags0 2
	FunctionFlags1 0
	EVHP 0
	EVATK 255
	EVDEF 0
	EVSPE 0
	EVSPA 100
	EVSPD 0
	HealAmount 0
	PPGain 83
	Friendship1 83
	Friendship2 64
	Friendship3 32
	Unk1F 0
	Unk20 0
