.align 4

Item130:
	Price 0
	HeldEffect 1
	HeldArgument 130
	NaturalGiftEffect 100
	FlingEffect 10
	FlingPower 0
	NaturalGiftPower 0
	Packed 0
	FieldEffect 100
	BattleEffect 0
	HasBattleStats 0
	ItemClass 0
	Consumable 0
	SortIndex 0
Item130_BattleStats:
	CureInflict 145
	Boost 0, 0, 0, 0
	FunctionFlags0 0
	FunctionFlags1 0
	EVHP 0
	EVATK 0
	EVDEF 0
	EVSPE 0
	EVSPA 0
	EVSPD 0
	HealAmount 0
	PPGain 83
	Friendship1 83
	Friendship2 75
	Friendship3 0
	Unk1F 0
	Unk20 0
