.align 4

Item563:
	Price 516
	HeldEffect 0
	HeldArgument 0
	NaturalGiftEffect 101
	FlingEffect 10
	FlingPower 0
	NaturalGiftPower 0
	Packed 0
	FieldEffect 0
	BattleEffect 0
	HasBattleStats 0
	ItemClass 0
	Consumable 0
	SortIndex 0
Item563_BattleStats:
	CureInflict 83
	Boost 1, 0, 0, 8
	FunctionFlags0 1
	FunctionFlags1 3
	EVHP 0
	EVATK 1
	EVDEF 1
	EVSPE 0
	EVSPA 100
	EVSPD 100
	HealAmount 0
	PPGain 83
	Friendship1 83
	Friendship2 0
	Friendship3 72
	Unk1F 0
	Unk20 0
