.align 4

Item298:
	Price 256
	HeldEffect 0
	HeldArgument 0
	NaturalGiftEffect 100
	FlingEffect 20
	FlingPower 0
	NaturalGiftPower 0
	Packed 6
	FieldEffect 0
	BattleEffect 2
	HasBattleStats 2
	ItemClass 5
	Consumable 0
	SortIndex 0
Item298_BattleStats:
	CureInflict 199
	Boost 0, 0, 0, 4
	FunctionFlags0 0
	FunctionFlags1 0
	EVHP 0
	EVATK 0
	EVDEF 0
	EVSPE 0
	EVSPA 0
	EVSPD 0
	HealAmount 0
	PPGain 83
	Friendship1 83
	Friendship2 72
	Friendship3 0
	Unk1F 0
	Unk20 0
