.align 4

Item309:
	Price 1800
	HeldEffect 1
	HeldArgument 90
	NaturalGiftEffect 90
	FlingEffect 10
	FlingPower 0
	NaturalGiftPower 0
	Packed 0
	FieldEffect 0
	BattleEffect 0
	HasBattleStats 0
	ItemClass 0
	Consumable 0
	SortIndex 0
Item309_BattleStats:
	CureInflict 139
	Boost 0, 0, 0, 0
	FunctionFlags0 1
	FunctionFlags1 0
	EVHP 0
	EVATK 1
	EVDEF 0
	EVSPE 0
	EVSPA 20
	EVSPD 0
	HealAmount 0
	PPGain 83
	Friendship1 83
	Friendship2 201
	Friendship3 0
	Unk1F 0
	Unk20 0
