.align 4

Item549:
	Price 1550
	HeldEffect 2
	HeldArgument 65
	NaturalGiftEffect 95
	FlingEffect 10
	FlingPower 0
	NaturalGiftPower 0
	Packed 0
	FieldEffect 0
	BattleEffect 0
	HasBattleStats 0
	ItemClass 0
	Consumable 0
	SortIndex 0
Item549_BattleStats:
	CureInflict 74
	Boost 1, 0, 0, 5
	FunctionFlags0 5
	FunctionFlags1 0
	EVHP 0
	EVATK 255
	EVDEF 0
	EVSPE 0
	EVSPA 100
	EVSPD 0
	HealAmount 0
	PPGain 83
	Friendship1 83
	Friendship2 72
	Friendship3 0
	Unk1F 0
	Unk20 0
