.align 4

Item361:
	Price 3341
	HeldEffect 0
	HeldArgument 0
	NaturalGiftEffect 101
	FlingEffect 10
	FlingPower 0
	NaturalGiftPower 0
	Packed 0
	FieldEffect 0
	BattleEffect 0
	HasBattleStats 0
	ItemClass 0
	Consumable 0
	SortIndex 0
Item361_BattleStats:
	CureInflict 220
	Boost 0, 0, 0, 7
	FunctionFlags0 0
	FunctionFlags1 0
	EVHP 0
	EVATK 0
	EVDEF 0
	EVSPE 0
	EVSPA 0
	EVSPD 0
	HealAmount 0
	PPGain 83
	Friendship1 83
	Friendship2 32
	Friendship3 16
	Unk1F 0
	Unk20 0
