.align 4

Item585:
	Price 1553
	HeldEffect 2
	HeldArgument 95
	NaturalGiftEffect 100
	FlingEffect 15
	FlingPower 0
	NaturalGiftPower 0
	Packed 0
	FieldEffect 0
	BattleEffect 0
	HasBattleStats 0
	ItemClass 0
	Consumable 0
	SortIndex 0
Item585_BattleStats:
	CureInflict 71
	Boost 0, 0, 0, 0
	FunctionFlags0 3
	FunctionFlags1 0
	EVHP 0
	EVATK 255
	EVDEF 0
	EVSPE 0
	EVSPA 30
	EVSPD 0
	HealAmount 0
	PPGain 83
	Friendship1 83
	Friendship2 72
	Friendship3 0
	Unk1F 0
	Unk20 0
