.align 4

Item608:
	Price 529
	HeldEffect 0
	HeldArgument 0
	NaturalGiftEffect 100
	FlingEffect 30
	FlingPower 1
	NaturalGiftPower 0
	Packed 0
	FieldEffect 0
	BattleEffect 0
	HasBattleStats 0
	ItemClass 0
	Consumable 0
	SortIndex 0
Item608_BattleStats:
	CureInflict 108
	Boost 1, 0, 0, 0
	FunctionFlags0 1
	FunctionFlags1 0
	EVHP 0
	EVATK 255
	EVDEF 0
	EVSPE 0
	EVSPA 0
	EVSPD 0
	HealAmount 0
	PPGain 83
	Friendship1 83
	Friendship2 88
	Friendship3 128
	Unk1F 0
	Unk20 0
