.align 4

Item489:
	Price 515
	HeldEffect 0
	HeldArgument 0
	NaturalGiftEffect 101
	FlingEffect 20
	FlingPower 0
	NaturalGiftPower 0
	Packed 0
	FieldEffect 0
	BattleEffect 0
	HasBattleStats 0
	ItemClass 0
	Consumable 0
	SortIndex 0
Item489_BattleStats:
	CureInflict 66
	Boost 1, 0, 0, 7
	FunctionFlags0 1
	FunctionFlags1 2
	EVHP 6
	EVATK 1
	EVDEF 1
	EVSPE 1
	EVSPA 0
	EVSPD 0
	HealAmount 0
	PPGain 83
	Friendship1 83
	Friendship2 32
	Friendship3 0
	Unk1F 0
	Unk20 0
