.align 4

Item312:
	Price 3339
	HeldEffect 0
	HeldArgument 0
	NaturalGiftEffect 101
	FlingEffect 5
	FlingPower 0
	NaturalGiftPower 0
	Packed 0
	FieldEffect 0
	BattleEffect 0
	HasBattleStats 0
	ItemClass 0
	Consumable 0
	SortIndex 0
Item312_BattleStats:
	CureInflict 102
	Boost 0, 0, 0, 6
	FunctionFlags0 0
	FunctionFlags1 0
	EVHP 0
	EVATK 0
	EVDEF 0
	EVSPE 0
	EVSPA 0
	EVSPD 0
	HealAmount 0
	PPGain 83
	Friendship1 83
	Friendship2 32
	Friendship3 8
	Unk1F 0
	Unk20 0
