.align 4

Item446:
	Price 2821
	HeldEffect 0
	HeldArgument 0
	NaturalGiftEffect 101
	FlingEffect 20
	FlingPower 0
	NaturalGiftPower 0
	Packed 0
	FieldEffect 0
	BattleEffect 0
	HasBattleStats 0
	ItemClass 0
	Consumable 0
	SortIndex 0
Item446_BattleStats:
	CureInflict 10
	Boost 1, 0, 0, 11
	FunctionFlags0 0
	FunctionFlags1 0
	EVHP 0
	EVATK 0
	EVDEF 0
	EVSPE 0
	EVSPA 0
	EVSPD 0
	HealAmount 0
	PPGain 83
	Friendship1 83
	Friendship2 16
	Friendship3 0
	Unk1F 0
	Unk20 0
