.align 4

Item321:
	Price 512
	HeldEffect 0
	HeldArgument 0
	NaturalGiftEffect 100
	FlingEffect 20
	FlingPower 0
	NaturalGiftPower 0
	Packed 0
	FieldEffect 0
	BattleEffect 0
	HasBattleStats 0
	ItemClass 0
	Consumable 0
	SortIndex 0
Item321_BattleStats:
	CureInflict 205
	Boost 0, 0, 0, 0
	FunctionFlags0 1
	FunctionFlags1 2
	EVHP 0
	EVATK 255
	EVDEF 255
	EVSPE 0
	EVSPA 0
	EVSPD 0
	HealAmount 0
	PPGain 83
	Friendship1 83
	Friendship2 88
	Friendship3 128
	Unk1F 0
	Unk20 0
