.align 4

Item35:
	Price 1024
	HeldEffect 1
	HeldArgument 15
	NaturalGiftEffect 90
	FlingEffect 20
	FlingPower 0
	NaturalGiftPower 0
	Packed 8
	FieldEffect 100
	BattleEffect 4
	HasBattleStats 5
	ItemClass 6
	Consumable 0
	SortIndex 0
Item35_BattleStats:
	CureInflict 42
	Boost 0, 0, 0, 0
	FunctionFlags0 0
	FunctionFlags1 0
	EVHP 0
	EVATK 0
	EVDEF 0
	EVSPE 0
	EVSPA 0
	EVSPD 0
	HealAmount 0
	PPGain 83
	Friendship1 83
	Friendship2 73
	Friendship3 128
	Unk1F 0
	Unk20 0
