.align 4

Item42:
	Price 6
	HeldEffect 1
	HeldArgument 25
	NaturalGiftEffect 95
	FlingEffect 20
	FlingPower 0
	NaturalGiftPower 82
	Packed 0
	FieldEffect 0
	BattleEffect 0
	HasBattleStats 0
	ItemClass 0
	Consumable 0
	SortIndex 0
Item42_BattleStats:
	CureInflict 29
	Boost 0, 0, 0, 0
	FunctionFlags0 0
	FunctionFlags1 0
	EVHP 0
	EVATK 0
	EVDEF 0
	EVSPE 0
	EVSPA 0
	EVSPD 0
	HealAmount 0
	PPGain 83
	Friendship1 83
	Friendship2 72
	Friendship3 0
	Unk1F 0
	Unk20 0
