.align 4

Item536:
	Price 1547
	HeldEffect 2
	HeldArgument 65
	NaturalGiftEffect 90
	FlingEffect 10
	FlingPower 0
	NaturalGiftPower 0
	Packed 0
	FieldEffect 0
	BattleEffect 0
	HasBattleStats 0
	ItemClass 0
	Consumable 0
	SortIndex 0
Item536_BattleStats:
	CureInflict 73
	Boost 0, 0, 0, 0
	FunctionFlags0 6
	FunctionFlags1 0
	EVHP 0
	EVATK 255
	EVDEF 0
	EVSPE 0
	EVSPA 50
	EVSPD 0
	HealAmount 0
	PPGain 83
	Friendship1 83
	Friendship2 72
	Friendship3 0
	Unk1F 0
	Unk20 0
