.align 4

Item316:
	Price 256
	HeldEffect 0
	HeldArgument 0
	NaturalGiftEffect 101
	FlingEffect 40
	FlingPower 0
	NaturalGiftPower 0
	Packed 17
	FieldEffect 0
	BattleEffect 1
	HasBattleStats 0
	ItemClass 0
	Consumable 0
	SortIndex 0
Item316_BattleStats:
	CureInflict 113
	Boost 0, 0, 0, 0
	FunctionFlags0 0
	FunctionFlags1 0
	EVHP 0
	EVATK 0
	EVDEF 0
	EVSPE 0
	EVSPA 0
	EVSPD 0
	HealAmount 0
	PPGain 83
	Friendship1 83
	Friendship2 88
	Friendship3 160
	Unk1F 0
	Unk20 0
