.align 4

Item590:
	Price 512
	HeldEffect 0
	HeldArgument 0
	NaturalGiftEffect 101
	FlingEffect 20
	FlingPower 0
	NaturalGiftPower 0
	Packed 0
	FieldEffect 0
	BattleEffect 0
	HasBattleStats 0
	ItemClass 0
	Consumable 0
	SortIndex 0
Item590_BattleStats:
	CureInflict 101
	Boost 1, 0, 0, 0
	FunctionFlags0 3
	FunctionFlags1 0
	EVHP 0
	EVATK 255
	EVDEF 0
	EVSPE 0
	EVSPA 100
	EVSPD 0
	HealAmount 0
	PPGain 83
	Friendship1 83
	Friendship2 80
	Friendship3 33
	Unk1F 0
	Unk20 0
