.align 4

Item103:
	Price 512
	HeldEffect 0
	HeldArgument 0
	NaturalGiftEffect 85
	FlingEffect 40
	FlingPower 0
	NaturalGiftPower 0
	Packed 0
	FieldEffect 0
	BattleEffect 0
	HasBattleStats 0
	ItemClass 0
	Consumable 0
	SortIndex 0
Item103_BattleStats:
	CureInflict 59
	Boost 0, 0, 0, 0
	FunctionFlags0 2
	FunctionFlags1 0
	EVHP 0
	EVATK 254
	EVDEF 0
	EVSPE 0
	EVSPA 0
	EVSPD 0
	HealAmount 0
	PPGain 83
	Friendship1 83
	Friendship2 88
	Friendship3 161
	Unk1F 0
	Unk20 0
