.align 4

Item594:
	Price 10
	HeldEffect 1
	HeldArgument 15
	NaturalGiftEffect 100
	FlingEffect 20
	FlingPower 1
	NaturalGiftPower 82
	Packed 0
	FieldEffect 0
	BattleEffect 0
	HasBattleStats 0
	ItemClass 0
	Consumable 0
	SortIndex 0
Item594_BattleStats:
	CureInflict 104
	Boost 1, 0, 0, 0
	FunctionFlags0 0
	FunctionFlags1 0
	EVHP 0
	EVATK 0
	EVDEF 0
	EVSPE 0
	EVSPA 0
	EVSPD 0
	HealAmount 0
	PPGain 83
	Friendship1 83
	Friendship2 72
	Friendship3 0
	Unk1F 0
	Unk20 0
