.align 4

Item211:
	Price 1800
	HeldEffect 1
	HeldArgument 70
	NaturalGiftEffect 90
	FlingEffect 25
	FlingPower 0
	NaturalGiftPower 0
	Packed 0
	FieldEffect 0
	BattleEffect 0
	HasBattleStats 0
	ItemClass 0
	Consumable 0
	SortIndex 0
Item211_BattleStats:
	CureInflict 138
	Boost 0, 0, 0, 0
	FunctionFlags0 2
	FunctionFlags1 0
	EVHP 0
	EVATK 1
	EVDEF 0
	EVSPE 0
	EVSPA 10
	EVSPD 0
	HealAmount 0
	PPGain 83
	Friendship1 83
	Friendship2 73
	Friendship3 0
	Unk1F 0
	Unk20 0
