.align 4

Item422:
	Price 1036
	HeldEffect 1
	HeldArgument 65
	NaturalGiftEffect 95
	FlingEffect 15
	FlingPower 0
	NaturalGiftPower 0
	Packed 1
	FieldEffect 10
	BattleEffect 1
	HasBattleStats 0
	ItemClass 0
	Consumable 0
	SortIndex 10
Item422_BattleStats:
	CureInflict 19
	Boost 1, 0, 0, 0
	FunctionFlags0 0
	FunctionFlags1 0
	EVHP 0
	EVATK 0
	EVDEF 0
	EVSPE 0
	EVSPA 0
	EVSPD 0
	HealAmount 0
	PPGain 83
	Friendship1 83
	Friendship2 73
	Friendship3 0
	Unk1F 0
	Unk20 0
