.align 4

Item165:
	Price 0
	HeldEffect 1
	HeldArgument 50
	NaturalGiftEffect 101
	FlingEffect 1
	FlingPower 0
	NaturalGiftPower 0
	Packed 0
	FieldEffect 0
	BattleEffect 0
	HasBattleStats 0
	ItemClass 0
	Consumable 0
	SortIndex 0
Item165_BattleStats:
	CureInflict 254
	Boost 0, 0, 231, 9
	FunctionFlags0 0
	FunctionFlags1 0
	EVHP 0
	EVATK 0
	EVDEF 0
	EVSPE 0
	EVSPA 0
	EVSPD 0
	HealAmount 0
	PPGain 83
	Friendship1 83
	Friendship2 9
	Friendship3 0
	Unk1F 0
	Unk20 0
