.align 4

Item128:
	Price 1034
	HeldEffect 1
	HeldArgument 35
	NaturalGiftEffect 85
	FlingEffect 15
	FlingPower 0
	NaturalGiftPower 0
	Packed 8
	FieldEffect 100
	BattleEffect 4
	HasBattleStats 5
	ItemClass 6
	Consumable 0
	SortIndex 0
Item128_BattleStats:
	CureInflict 42
	Boost 0, 0, 0, 0
	FunctionFlags0 0
	FunctionFlags1 0
	EVHP 0
	EVATK 0
	EVDEF 0
	EVSPE 0
	EVSPA 0
	EVSPD 0
	HealAmount 0
	PPGain 83
	Friendship1 83
	Friendship2 73
	Friendship3 0
	Unk1F 0
	Unk20 0
