.align 4

Item430:
	Price 1544
	HeldEffect 2
	HeldArgument 80
	NaturalGiftEffect 100
	FlingEffect 10
	FlingPower 0
	NaturalGiftPower 0
	Packed 0
	FieldEffect 0
	BattleEffect 0
	HasBattleStats 0
	ItemClass 0
	Consumable 0
	SortIndex 0
Item430_BattleStats:
	CureInflict 72
	Boost 0, 0, 0, 0
	FunctionFlags0 4
	FunctionFlags1 0
	EVHP 0
	EVATK 255
	EVDEF 0
	EVSPE 0
	EVSPA 10
	EVSPD 0
	HealAmount 0
	PPGain 83
	Friendship1 83
	Friendship2 72
	Friendship3 0
	Unk1F 0
	Unk20 0
