.align 4

Item59:
	Price 1038
	HeldEffect 2
	HeldArgument 110
	NaturalGiftEffect 70
	FlingEffect 5
	FlingPower 0
	NaturalGiftPower 0
	Packed 3
	FieldEffect 10
	BattleEffect 1
	HasBattleStats 0
	ItemClass 0
	Consumable 0
	SortIndex 0
Item59_BattleStats:
	CureInflict 4
	Boost 1, 0, 0, 5
	FunctionFlags0 0
	FunctionFlags1 0
	EVHP 0
	EVATK 0
	EVDEF 0
	EVSPE 0
	EVSPA 0
	EVSPD 0
	HealAmount 0
	PPGain 83
	Friendship1 83
	Friendship2 72
	Friendship3 0
	Unk1F 0
	Unk20 0
