.align 4

Item195:
	Price 256
	HeldEffect 0
	HeldArgument 0
	NaturalGiftEffect 101
	FlingEffect 5
	FlingPower 0
	NaturalGiftPower 0
	Packed 20
	FieldEffect 0
	BattleEffect 2
	HasBattleStats 4
	ItemClass 4
	Consumable 0
	SortIndex 0
Item195_BattleStats:
	CureInflict 114
	Boost 0, 0, 0, 8
	FunctionFlags0 0
	FunctionFlags1 0
	EVHP 0
	EVATK 0
	EVDEF 0
	EVSPE 0
	EVSPA 0
	EVSPD 0
	HealAmount 0
	PPGain 83
	Friendship1 83
	Friendship2 0
	Friendship3 41
	Unk1F 0
	Unk20 0
