.align 4

Item568:
	Price 512
	HeldEffect 0
	HeldArgument 0
	NaturalGiftEffect 100
	FlingEffect 30
	FlingPower 0
	NaturalGiftPower 0
	Packed 0
	FieldEffect 0
	BattleEffect 0
	HasBattleStats 0
	ItemClass 0
	Consumable 0
	SortIndex 0
Item568_BattleStats:
	CureInflict 87
	Boost 1, 0, 0, 0
	FunctionFlags0 1
	FunctionFlags1 3
	EVHP 0
	EVATK 255
	EVDEF 255
	EVSPE 0
	EVSPA 100
	EVSPD 100
	HealAmount 0
	PPGain 83
	Friendship1 83
	Friendship2 88
	Friendship3 33
	Unk1F 0
	Unk20 0
