.align 4

Item61:
	Price 1546
	HeldEffect 2
	HeldArgument 65
	NaturalGiftEffect 100
	FlingEffect 20
	FlingPower 0
	NaturalGiftPower 0
	Packed 0
	FieldEffect 0
	BattleEffect 0
	HasBattleStats 0
	ItemClass 0
	Consumable 0
	SortIndex 0
Item61_BattleStats:
	CureInflict 70
	Boost 0, 0, 0, 0
	FunctionFlags0 5
	FunctionFlags1 0
	EVHP 0
	EVATK 255
	EVDEF 0
	EVSPE 0
	EVSPA 10
	EVSPD 0
	HealAmount 0
	PPGain 83
	Friendship1 83
	Friendship2 72
	Friendship3 0
	Unk1F 0
	Unk20 0
