.align 4

Item230:
	Price 512
	HeldEffect 0
	HeldArgument 0
	NaturalGiftEffect 100
	FlingEffect 20
	FlingPower 0
	NaturalGiftPower 0
	Packed 0
	FieldEffect 0
	BattleEffect 0
	HasBattleStats 0
	ItemClass 0
	Consumable 0
	SortIndex 0
Item230_BattleStats:
	CureInflict 24
	Boost 0, 0, 0, 5
	FunctionFlags0 7
	FunctionFlags1 0
	EVHP 0
	EVATK 254
	EVDEF 0
	EVSPE 0
	EVSPA 0
	EVSPD 0
	HealAmount 0
	PPGain 83
	Friendship1 83
	Friendship2 88
	Friendship3 0
	Unk1F 0
	Unk20 0
