.align 4

Item223:
	Price 1025
	HeldEffect 1
	HeldArgument 100
	NaturalGiftEffect 50
	FlingEffect 5
	FlingPower 0
	NaturalGiftPower 0
	Packed 6
	FieldEffect 100
	BattleEffect 2
	HasBattleStats 2
	ItemClass 5
	Consumable 0
	SortIndex 0
Item223_BattleStats:
	CureInflict 76
	Boost 0, 0, 0, 0
	FunctionFlags0 0
	FunctionFlags1 0
	EVHP 0
	EVATK 0
	EVDEF 0
	EVSPE 0
	EVSPA 0
	EVSPD 0
	HealAmount 0
	PPGain 83
	Friendship1 83
	Friendship2 201
	Friendship3 0
	Unk1F 0
	Unk20 0
