.align 4

Item433:
	Price 2573
	HeldEffect 0
	HeldArgument 0
	NaturalGiftEffect 101
	FlingEffect 5
	FlingPower 249
	NaturalGiftPower 0
	Packed 0
	FieldEffect 0
	BattleEffect 0
	HasBattleStats 0
	ItemClass 0
	Consumable 0
	SortIndex 0
Item433_BattleStats:
	CureInflict 3
	Boost 1, 0, 0, 10
	FunctionFlags0 0
	FunctionFlags1 0
	EVHP 0
	EVATK 0
	EVDEF 0
	EVSPE 0
	EVSPA 0
	EVSPD 0
	HealAmount 0
	PPGain 83
	Friendship1 83
	Friendship2 64
	Friendship3 0
	Unk1F 0
	Unk20 0
