.align 4

Item477:
	Price 269
	HeldEffect 0
	HeldArgument 0
	NaturalGiftEffect 101
	FlingEffect 15
	FlingPower 0
	NaturalGiftPower 0
	Packed 65535
	FieldEffect 0
	BattleEffect 2
	HasBattleStats 3
	ItemClass 3
	Consumable 0
	SortIndex 0
Item477_BattleStats:
	CureInflict 29
	Boost 1, 0, 0, 0
	FunctionFlags0 0
	FunctionFlags1 0
	EVHP 0
	EVATK 0
	EVDEF 0
	EVSPE 0
	EVSPA 0
	EVSPD 0
	HealAmount 0
	PPGain 83
	Friendship1 83
	Friendship2 88
	Friendship3 130
	Unk1F 0
	Unk20 0
