.align 4

Item601:
	Price 529
	HeldEffect 0
	HeldArgument 0
	NaturalGiftEffect 101
	FlingEffect 10
	FlingPower 0
	NaturalGiftPower 0
	Packed 0
	FieldEffect 0
	BattleEffect 0
	HasBattleStats 0
	ItemClass 0
	Consumable 0
	SortIndex 0
Item601_BattleStats:
	CureInflict 109
	Boost 1, 0, 0, 7
	FunctionFlags0 3
	FunctionFlags1 4
	EVHP 5
	EVATK 2
	EVDEF 2
	EVSPE 2
	EVSPA 0
	EVSPD 0
	HealAmount 0
	PPGain 83
	Friendship1 83
	Friendship2 2
	Friendship3 64
	Unk1F 0
	Unk20 0
