.align 4

Item305:
	Price 1027
	HeldEffect 1
	HeldArgument 50
	NaturalGiftEffect 100
	FlingEffect 15
	FlingPower 0
	NaturalGiftPower 0
	Packed 5
	FieldEffect 50
	BattleEffect 1
	HasBattleStats 15
	ItemClass 15
	Consumable 0
	SortIndex 0
Item305_BattleStats:
	CureInflict 202
	Boost 0, 0, 0, 0
	FunctionFlags0 0
	FunctionFlags1 0
	EVHP 0
	EVATK 0
	EVDEF 0
	EVSPE 0
	EVSPA 0
	EVSPD 0
	HealAmount 0
	PPGain 83
	Friendship1 83
	Friendship2 73
	Friendship3 0
	Unk1F 0
	Unk20 0
