Species_436:
	LearnsetEntry 33, 1
	LearnsetEntry 93, 1
	LearnsetEntry 95, 5
	LearnsetEntry 286, 9
	LearnsetEntry 109, 11
	LearnsetEntry 149, 15
	LearnsetEntry 334, 19
	LearnsetEntry 185, 21
	LearnsetEntry 219, 25
	LearnsetEntry 248, 29
	LearnsetEntry 319, 31
	LearnsetEntry 360, 35
	LearnsetEntry 326, 39
	LearnsetEntry 371, 41
	LearnsetEntry 377, 45
	LearnsetEntry 484, 49
	LearnsetEntry 65535, 65535
