Species_335:
	LearnsetEntry 10, 1
	LearnsetEntry 43, 1
	LearnsetEntry 98, 5
	LearnsetEntry 210, 8
	LearnsetEntry 228, 12
	LearnsetEntry 468, 15
	LearnsetEntry 163, 19
	LearnsetEntry 279, 22
	LearnsetEntry 306, 26
	LearnsetEntry 206, 29
	LearnsetEntry 373, 33
	LearnsetEntry 197, 36
	LearnsetEntry 404, 40
	LearnsetEntry 269, 43
	LearnsetEntry 14, 47
	LearnsetEntry 370, 50
	LearnsetEntry 65535, 65535
