Species_320:
	LearnsetEntry 150, 1
	LearnsetEntry 45, 4
	LearnsetEntry 55, 7
	LearnsetEntry 205, 10
	LearnsetEntry 250, 13
	LearnsetEntry 310, 16
	LearnsetEntry 352, 19
	LearnsetEntry 54, 22
	LearnsetEntry 362, 25
	LearnsetEntry 156, 29
	LearnsetEntry 291, 33
	LearnsetEntry 133, 37
	LearnsetEntry 323, 41
	LearnsetEntry 340, 45
	LearnsetEntry 56, 49
	LearnsetEntry 484, 53
	LearnsetEntry 65535, 65535
