Species_513:
	LearnsetEntry 10, 1
	LearnsetEntry 589, 1
	LearnsetEntry 43, 4
	LearnsetEntry 122, 7
	LearnsetEntry 510, 10
	LearnsetEntry 154, 13
	LearnsetEntry 281, 16
	LearnsetEntry 44, 19
	LearnsetEntry 481, 22
	LearnsetEntry 133, 25
	LearnsetEntry 374, 28
	LearnsetEntry 512, 31
	LearnsetEntry 126, 34
	LearnsetEntry 278, 37
	LearnsetEntry 363, 40
	LearnsetEntry 242, 43
	LearnsetEntry 65535, 65535
