Species_167:
	LearnsetEntry 40, 1
	LearnsetEntry 81, 1
	LearnsetEntry 184, 5
	LearnsetEntry 132, 8
	LearnsetEntry 141, 12
	LearnsetEntry 101, 15
	LearnsetEntry 425, 19
	LearnsetEntry 154, 22
	LearnsetEntry 389, 26
	LearnsetEntry 169, 29
	LearnsetEntry 97, 33
	LearnsetEntry 42, 36
	LearnsetEntry 94, 40
	LearnsetEntry 398, 43
	LearnsetEntry 440, 47
	LearnsetEntry 564, 50
	LearnsetEntry 65535, 65535
