Species_707:
	LearnsetEntry 587, 1
	LearnsetEntry 33, 1
	LearnsetEntry 584, 5
	LearnsetEntry 310, 8
	LearnsetEntry 319, 12
	LearnsetEntry 191, 15
	LearnsetEntry 577, 18
	LearnsetEntry 578, 23
	LearnsetEntry 492, 27
	LearnsetEntry 259, 32
	LearnsetEntry 429, 34
	LearnsetEntry 286, 36
	LearnsetEntry 278, 40
	LearnsetEntry 583, 43
	LearnsetEntry 478, 44
	LearnsetEntry 377, 50
	LearnsetEntry 65535, 65535
