Species_559:
	LearnsetEntry 43, 1
	LearnsetEntry 67, 1
	LearnsetEntry 28, 5
	LearnsetEntry 185, 9
	LearnsetEntry 29, 12
	LearnsetEntry 207, 16
	LearnsetEntry 280, 20
	LearnsetEntry 371, 23
	LearnsetEntry 498, 27
	LearnsetEntry 136, 31
	LearnsetEntry 184, 34
	LearnsetEntry 242, 38
	LearnsetEntry 263, 42
	LearnsetEntry 431, 45
	LearnsetEntry 264, 48
	LearnsetEntry 457, 50
	LearnsetEntry 65535, 65535
