Species_587:
	LearnsetEntry 84, 1
	LearnsetEntry 98, 4
	LearnsetEntry 39, 7
	LearnsetEntry 268, 10
	LearnsetEntry 209, 13
	LearnsetEntry 609, 15
	LearnsetEntry 228, 16
	LearnsetEntry 104, 19
	LearnsetEntry 351, 22
	LearnsetEntry 486, 26
	LearnsetEntry 512, 30
	LearnsetEntry 113, 34
	LearnsetEntry 227, 38
	LearnsetEntry 521, 42
	LearnsetEntry 97, 46
	LearnsetEntry 435, 50
	LearnsetEntry 65535, 65535
