Species_685:
	LearnsetEntry 230, 1
	LearnsetEntry 33, 1
	LearnsetEntry 584, 5
	LearnsetEntry 589, 8
	LearnsetEntry 313, 10
	LearnsetEntry 496, 13
	LearnsetEntry 178, 17
	LearnsetEntry 283, 21
	LearnsetEntry 312, 26
	LearnsetEntry 577, 31
	LearnsetEntry 412, 36
	LearnsetEntry 538, 41
	LearnsetEntry 273, 45
	LearnsetEntry 583, 49
	LearnsetEntry 113, 58
	LearnsetEntry 219, 67
	LearnsetEntry 65535, 65535
