Species_613:
	LearnsetEntry 45, 1
	LearnsetEntry 181, 5
	LearnsetEntry 117, 9
	LearnsetEntry 196, 13
	LearnsetEntry 589, 15
	LearnsetEntry 154, 17
	LearnsetEntry 362, 21
	LearnsetEntry 203, 25
	LearnsetEntry 204, 29
	LearnsetEntry 163, 33
	LearnsetEntry 175, 36
	LearnsetEntry 156, 41
	LearnsetEntry 59, 45
	LearnsetEntry 258, 49
	LearnsetEntry 37, 53
	LearnsetEntry 329, 57
	LearnsetEntry 65535, 65535
