Species_249:
	LearnsetEntry 18, 1
	LearnsetEntry 311, 1
	LearnsetEntry 16, 9
	LearnsetEntry 407, 15
	LearnsetEntry 326, 23
	LearnsetEntry 240, 29
	LearnsetEntry 56, 37
	LearnsetEntry 177, 43
	LearnsetEntry 386, 50
	LearnsetEntry 246, 57
	LearnsetEntry 219, 65
	LearnsetEntry 105, 71
	LearnsetEntry 248, 79
	LearnsetEntry 363, 85
	LearnsetEntry 347, 93
	LearnsetEntry 143, 99
	LearnsetEntry 65535, 65535
