Species_624:
	LearnsetEntry 10, 1
	LearnsetEntry 43, 6
	LearnsetEntry 210, 9
	LearnsetEntry 259, 14
	LearnsetEntry 185, 17
	LearnsetEntry 184, 22
	LearnsetEntry 232, 25
	LearnsetEntry 163, 30
	LearnsetEntry 372, 33
	LearnsetEntry 319, 38
	LearnsetEntry 373, 41
	LearnsetEntry 334, 46
	LearnsetEntry 400, 49
	LearnsetEntry 442, 54
	LearnsetEntry 14, 57
	LearnsetEntry 12, 62
	LearnsetEntry 65535, 65535
