Species_709:
	LearnsetEntry 532, 1
	LearnsetEntry 33, 1
	LearnsetEntry 109, 1
	LearnsetEntry 310, 5
	LearnsetEntry 74, 8
	LearnsetEntry 275, 13
	LearnsetEntry 185, 19
	LearnsetEntry 73, 23
	LearnsetEntry 174, 28
	LearnsetEntry 261, 31
	LearnsetEntry 571, 35
	LearnsetEntry 194, 39
	LearnsetEntry 566, 45
	LearnsetEntry 452, 49
	LearnsetEntry 421, 55
	LearnsetEntry 532, 62
	LearnsetEntry 65535, 65535
