Species_577:
	LearnsetEntry 149, 1
	LearnsetEntry 115, 3
	LearnsetEntry 205, 7
	LearnsetEntry 289, 10
	LearnsetEntry 237, 14
	LearnsetEntry 113, 16
	LearnsetEntry 204, 19
	LearnsetEntry 105, 24
	LearnsetEntry 473, 25
	LearnsetEntry 283, 28
	LearnsetEntry 248, 31
	LearnsetEntry 220, 33
	LearnsetEntry 94, 37
	LearnsetEntry 285, 40
	LearnsetEntry 377, 46
	LearnsetEntry 472, 48
	LearnsetEntry 65535, 65535
