Species_721:
	LearnsetEntry 592, 1
	LearnsetEntry 394, 1
	LearnsetEntry 36, 1
	LearnsetEntry 54, 8
	LearnsetEntry 114, 11
	LearnsetEntry 488, 15
	LearnsetEntry 352, 21
	LearnsetEntry 23, 28
	LearnsetEntry 503, 32
	LearnsetEntry 311, 40
	LearnsetEntry 34, 46
	LearnsetEntry 56, 50
	LearnsetEntry 394, 58
	LearnsetEntry 315, 65
	LearnsetEntry 153, 76
	LearnsetEntry 592, 85
	LearnsetEntry 65535, 65535
