Species_143:
	LearnsetEntry 33, 1
	LearnsetEntry 111, 4
	LearnsetEntry 133, 9
	LearnsetEntry 122, 12
	LearnsetEntry 498, 17
	LearnsetEntry 281, 20
	LearnsetEntry 34, 25
	LearnsetEntry 156, 28
	LearnsetEntry 173, 28
	LearnsetEntry 214, 33
	LearnsetEntry 205, 36
	LearnsetEntry 335, 41
	LearnsetEntry 187, 44
	LearnsetEntry 242, 49
	LearnsetEntry 484, 50
	LearnsetEntry 416, 57
	LearnsetEntry 65535, 65535
