Species_706:
	LearnsetEntry 200, 1
	LearnsetEntry 364, 1
	LearnsetEntry 33, 1
	LearnsetEntry 145, 1
	LearnsetEntry 71, 5
	LearnsetEntry 182, 9
	LearnsetEntry 117, 13
	LearnsetEntry 225, 18
	LearnsetEntry 240, 25
	LearnsetEntry 175, 28
	LearnsetEntry 34, 32
	LearnsetEntry 330, 38
	LearnsetEntry 406, 47
	LearnsetEntry 401, 50
	LearnsetEntry 438, 55
	LearnsetEntry 200, 63
	LearnsetEntry 65535, 65535
