Species_316:
	LearnsetEntry 1, 1
	LearnsetEntry 281, 5
	LearnsetEntry 139, 8
	LearnsetEntry 124, 10
	LearnsetEntry 133, 12
	LearnsetEntry 491, 17
	LearnsetEntry 227, 20
	LearnsetEntry 92, 25
	LearnsetEntry 254, 28
	LearnsetEntry 255, 28
	LearnsetEntry 256, 28
	LearnsetEntry 188, 33
	LearnsetEntry 380, 36
	LearnsetEntry 562, 41
	LearnsetEntry 378, 44
	LearnsetEntry 441, 49
	LearnsetEntry 65535, 65535
