Species_74:
	LearnsetEntry 33, 1
	LearnsetEntry 111, 1
	LearnsetEntry 300, 4
	LearnsetEntry 397, 6
	LearnsetEntry 205, 10
	LearnsetEntry 222, 12
	LearnsetEntry 88, 16
	LearnsetEntry 479, 18
	LearnsetEntry 523, 22
	LearnsetEntry 120, 24
	LearnsetEntry 446, 28
	LearnsetEntry 350, 30
	LearnsetEntry 89, 34
	LearnsetEntry 153, 36
	LearnsetEntry 38, 40
	LearnsetEntry 444, 42
	LearnsetEntry 65535, 65535
