Species_228:
	LearnsetEntry 43, 1
	LearnsetEntry 52, 1
	LearnsetEntry 336, 4
	LearnsetEntry 123, 8
	LearnsetEntry 46, 13
	LearnsetEntry 44, 16
	LearnsetEntry 316, 20
	LearnsetEntry 251, 25
	LearnsetEntry 424, 28
	LearnsetEntry 185, 32
	LearnsetEntry 373, 37
	LearnsetEntry 492, 40
	LearnsetEntry 53, 44
	LearnsetEntry 242, 49
	LearnsetEntry 417, 52
	LearnsetEntry 517, 56
	LearnsetEntry 65535, 65535
