Species_627:
	LearnsetEntry 64, 1
	LearnsetEntry 43, 1
	LearnsetEntry 31, 5
	LearnsetEntry 17, 10
	LearnsetEntry 468, 14
	LearnsetEntry 184, 19
	LearnsetEntry 332, 23
	LearnsetEntry 163, 28
	LearnsetEntry 432, 32
	LearnsetEntry 366, 37
	LearnsetEntry 403, 41
	LearnsetEntry 306, 46
	LearnsetEntry 507, 50
	LearnsetEntry 18, 55
	LearnsetEntry 413, 59
	LearnsetEntry 37, 64
	LearnsetEntry 65535, 65535
