Species_193:
	LearnsetEntry 33, 1
	LearnsetEntry 193, 1
	LearnsetEntry 98, 6
	LearnsetEntry 104, 11
	LearnsetEntry 49, 14
	LearnsetEntry 197, 17
	LearnsetEntry 48, 22
	LearnsetEntry 253, 27
	LearnsetEntry 228, 30
	LearnsetEntry 246, 33
	LearnsetEntry 95, 38
	LearnsetEntry 17, 43
	LearnsetEntry 103, 46
	LearnsetEntry 369, 49
	LearnsetEntry 403, 54
	LearnsetEntry 405, 57
	LearnsetEntry 65535, 65535
