Species_177:
	LearnsetEntry 64, 1
	LearnsetEntry 43, 1
	LearnsetEntry 101, 6
	LearnsetEntry 100, 9
	LearnsetEntry 381, 12
	LearnsetEntry 500, 17
	LearnsetEntry 466, 20
	LearnsetEntry 109, 23
	LearnsetEntry 273, 28
	LearnsetEntry 94, 33
	LearnsetEntry 357, 36
	LearnsetEntry 375, 39
	LearnsetEntry 248, 44
	LearnsetEntry 384, 47
	LearnsetEntry 385, 47
	LearnsetEntry 382, 50
	LearnsetEntry 65535, 65535
