Species_621:
	LearnsetEntry 43, 1
	LearnsetEntry 10, 1
	LearnsetEntry 468, 5
	LearnsetEntry 44, 9
	LearnsetEntry 184, 13
	LearnsetEntry 82, 18
	LearnsetEntry 163, 21
	LearnsetEntry 242, 25
	LearnsetEntry 337, 27
	LearnsetEntry 498, 31
	LearnsetEntry 279, 35
	LearnsetEntry 400, 40
	LearnsetEntry 525, 45
	LearnsetEntry 431, 49
	LearnsetEntry 276, 55
	LearnsetEntry 200, 62
	LearnsetEntry 65535, 65535
