Species_595:
	LearnsetEntry 81, 1
	LearnsetEntry 141, 1
	LearnsetEntry 169, 1
	LearnsetEntry 86, 4
	LearnsetEntry 103, 7
	LearnsetEntry 210, 12
	LearnsetEntry 527, 15
	LearnsetEntry 450, 18
	LearnsetEntry 380, 23
	LearnsetEntry 163, 26
	LearnsetEntry 486, 29
	LearnsetEntry 324, 34
	LearnsetEntry 97, 37
	LearnsetEntry 389, 40
	LearnsetEntry 435, 45
	LearnsetEntry 405, 48
	LearnsetEntry 65535, 65535
