Species_88:
	LearnsetEntry 1, 1
	LearnsetEntry 139, 1
	LearnsetEntry 106, 4
	LearnsetEntry 189, 7
	LearnsetEntry 50, 12
	LearnsetEntry 124, 15
	LearnsetEntry 426, 18
	LearnsetEntry 107, 21
	LearnsetEntry 374, 26
	LearnsetEntry 188, 29
	LearnsetEntry 482, 32
	LearnsetEntry 103, 37
	LearnsetEntry 441, 40
	LearnsetEntry 151, 43
	LearnsetEntry 562, 46
	LearnsetEntry 262, 48
	LearnsetEntry 65535, 65535
