Species_570:
	LearnsetEntry 10, 1
	LearnsetEntry 43, 1
	LearnsetEntry 228, 5
	LearnsetEntry 313, 9
	LearnsetEntry 154, 13
	LearnsetEntry 185, 17
	LearnsetEntry 184, 21
	LearnsetEntry 269, 25
	LearnsetEntry 492, 29
	LearnsetEntry 259, 33
	LearnsetEntry 97, 37
	LearnsetEntry 373, 41
	LearnsetEntry 386, 45
	LearnsetEntry 417, 49
	LearnsetEntry 286, 53
	LearnsetEntry 539, 57
	LearnsetEntry 65535, 65535
