Species_610:
	LearnsetEntry 10, 1
	LearnsetEntry 43, 4
	LearnsetEntry 372, 7
	LearnsetEntry 82, 10
	LearnsetEntry 530, 13
	LearnsetEntry 184, 16
	LearnsetEntry 163, 20
	LearnsetEntry 206, 24
	LearnsetEntry 337, 28
	LearnsetEntry 349, 32
	LearnsetEntry 269, 36
	LearnsetEntry 406, 41
	LearnsetEntry 14, 46
	LearnsetEntry 12, 50
	LearnsetEntry 200, 56
	LearnsetEntry 416, 61
	LearnsetEntry 65535, 65535
