Species_435:
	LearnsetEntry 10, 1
	LearnsetEntry 116, 1
	LearnsetEntry 139, 1
	LearnsetEntry 139, 4
	LearnsetEntry 103, 7
	LearnsetEntry 154, 10
	LearnsetEntry 108, 14
	LearnsetEntry 364, 18
	LearnsetEntry 163, 22
	LearnsetEntry 92, 27
	LearnsetEntry 491, 32
	LearnsetEntry 53, 34
	LearnsetEntry 400, 41
	LearnsetEntry 262, 51
	LearnsetEntry 562, 56
	LearnsetEntry 153, 61
	LearnsetEntry 65535, 65535
