Species_65:
	LearnsetEntry 100, 1
	LearnsetEntry 134, 1
	LearnsetEntry 93, 1
	LearnsetEntry 93, 16
	LearnsetEntry 50, 18
	LearnsetEntry 60, 21
	LearnsetEntry 357, 23
	LearnsetEntry 115, 26
	LearnsetEntry 427, 28
	LearnsetEntry 105, 31
	LearnsetEntry 477, 33
	LearnsetEntry 502, 36
	LearnsetEntry 94, 38
	LearnsetEntry 347, 41
	LearnsetEntry 248, 43
	LearnsetEntry 271, 46
	LearnsetEntry 65535, 65535
