Species_619:
	LearnsetEntry 1, 1
	LearnsetEntry 96, 5
	LearnsetEntry 197, 9
	LearnsetEntry 252, 13
	LearnsetEntry 3, 17
	LearnsetEntry 129, 21
	LearnsetEntry 347, 25
	LearnsetEntry 395, 29
	LearnsetEntry 409, 33
	LearnsetEntry 26, 37
	LearnsetEntry 369, 41
	LearnsetEntry 501, 45
	LearnsetEntry 340, 49
	LearnsetEntry 136, 50
	LearnsetEntry 179, 57
	LearnsetEntry 396, 61
	LearnsetEntry 65535, 65535
