Species_682:
	LearnsetEntry 230, 1
	LearnsetEntry 584, 1
	LearnsetEntry 186, 6
	LearnsetEntry 316, 8
	LearnsetEntry 497, 13
	LearnsetEntry 347, 17
	LearnsetEntry 577, 21
	LearnsetEntry 312, 25
	LearnsetEntry 213, 29
	LearnsetEntry 585, 31
	LearnsetEntry 204, 35
	LearnsetEntry 175, 38
	LearnsetEntry 581, 42
	LearnsetEntry 285, 44
	LearnsetEntry 94, 48
	LearnsetEntry 574, 50
	LearnsetEntry 65535, 65535
