Species_643:
	LearnsetEntry 424, 1
	LearnsetEntry 82, 1
	LearnsetEntry 286, 8
	LearnsetEntry 246, 15
	LearnsetEntry 53, 22
	LearnsetEntry 225, 29
	LearnsetEntry 163, 36
	LearnsetEntry 326, 43
	LearnsetEntry 558, 50
	LearnsetEntry 406, 54
	LearnsetEntry 286, 64
	LearnsetEntry 242, 71
	LearnsetEntry 126, 78
	LearnsetEntry 200, 85
	LearnsetEntry 304, 92
	LearnsetEntry 551, 100
	LearnsetEntry 65535, 65535
