Species_385:
	LearnsetEntry 273, 1
	LearnsetEntry 93, 1
	LearnsetEntry 156, 5
	LearnsetEntry 129, 10
	LearnsetEntry 270, 15
	LearnsetEntry 94, 20
	LearnsetEntry 287, 25
	LearnsetEntry 156, 30
	LearnsetEntry 428, 35
	LearnsetEntry 38, 40
	LearnsetEntry 356, 45
	LearnsetEntry 361, 50
	LearnsetEntry 248, 55
	LearnsetEntry 322, 60
	LearnsetEntry 387, 65
	LearnsetEntry 353, 70
	LearnsetEntry 65535, 65535
