Species_644:
	LearnsetEntry 422, 1
	LearnsetEntry 82, 1
	LearnsetEntry 286, 8
	LearnsetEntry 246, 15
	LearnsetEntry 85, 22
	LearnsetEntry 225, 29
	LearnsetEntry 163, 36
	LearnsetEntry 428, 43
	LearnsetEntry 559, 50
	LearnsetEntry 337, 54
	LearnsetEntry 286, 64
	LearnsetEntry 242, 71
	LearnsetEntry 87, 78
	LearnsetEntry 200, 85
	LearnsetEntry 304, 92
	LearnsetEntry 550, 100
	LearnsetEntry 65535, 65535
