Species_515:
	LearnsetEntry 10, 1
	LearnsetEntry 589, 1
	LearnsetEntry 43, 4
	LearnsetEntry 122, 7
	LearnsetEntry 55, 10
	LearnsetEntry 154, 13
	LearnsetEntry 346, 16
	LearnsetEntry 44, 19
	LearnsetEntry 503, 22
	LearnsetEntry 269, 25
	LearnsetEntry 374, 28
	LearnsetEntry 512, 31
	LearnsetEntry 362, 34
	LearnsetEntry 278, 37
	LearnsetEntry 363, 40
	LearnsetEntry 242, 43
	LearnsetEntry 65535, 65535
