Species_688:
	LearnsetEntry 504, 1
	LearnsetEntry 10, 1
	LearnsetEntry 28, 1
	LearnsetEntry 55, 4
	LearnsetEntry 110, 7
	LearnsetEntry 154, 10
	LearnsetEntry 163, 13
	LearnsetEntry 189, 18
	LearnsetEntry 128, 20
	LearnsetEntry 397, 24
	LearnsetEntry 246, 28
	LearnsetEntry 468, 32
	LearnsetEntry 210, 37
	LearnsetEntry 400, 41
	LearnsetEntry 534, 45
	LearnsetEntry 238, 49
	LearnsetEntry 65535, 65535
