Species_216:
	LearnsetEntry 374, 1
	LearnsetEntry 343, 1
	LearnsetEntry 10, 1
	LearnsetEntry 608, 1
	LearnsetEntry 122, 1
	LearnsetEntry 313, 1
	LearnsetEntry 154, 8
	LearnsetEntry 185, 15
	LearnsetEntry 230, 22
	LearnsetEntry 589, 25
	LearnsetEntry 163, 29
	LearnsetEntry 204, 36
	LearnsetEntry 156, 43
	LearnsetEntry 173, 43
	LearnsetEntry 37, 50
	LearnsetEntry 374, 57
	LearnsetEntry 65535, 65535
