Species_532:
	LearnsetEntry 1, 1
	LearnsetEntry 43, 1
	LearnsetEntry 116, 4
	LearnsetEntry 117, 8
	LearnsetEntry 67, 12
	LearnsetEntry 88, 16
	LearnsetEntry 358, 20
	LearnsetEntry 498, 24
	LearnsetEntry 339, 28
	LearnsetEntry 157, 31
	LearnsetEntry 223, 34
	LearnsetEntry 184, 37
	LearnsetEntry 359, 40
	LearnsetEntry 444, 43
	LearnsetEntry 264, 46
	LearnsetEntry 276, 49
	LearnsetEntry 65535, 65535
