Species_702:
	LearnsetEntry 33, 1
	LearnsetEntry 39, 1
	LearnsetEntry 84, 7
	LearnsetEntry 268, 11
	LearnsetEntry 204, 14
	LearnsetEntry 570, 17
	LearnsetEntry 609, 20
	LearnsetEntry 86, 23
	LearnsetEntry 521, 26
	LearnsetEntry 156, 30
	LearnsetEntry 173, 31
	LearnsetEntry 451, 34
	LearnsetEntry 494, 39
	LearnsetEntry 583, 42
	LearnsetEntry 87, 45
	LearnsetEntry 435, 50
	LearnsetEntry 65535, 65535
