Species_250:
	LearnsetEntry 18, 1
	LearnsetEntry 311, 1
	LearnsetEntry 16, 9
	LearnsetEntry 413, 15
	LearnsetEntry 326, 23
	LearnsetEntry 241, 29
	LearnsetEntry 126, 37
	LearnsetEntry 221, 43
	LearnsetEntry 386, 50
	LearnsetEntry 246, 57
	LearnsetEntry 219, 65
	LearnsetEntry 105, 71
	LearnsetEntry 248, 79
	LearnsetEntry 363, 85
	LearnsetEntry 347, 93
	LearnsetEntry 143, 99
	LearnsetEntry 65535, 65535
