Species_218:
	LearnsetEntry 281, 1
	LearnsetEntry 123, 1
	LearnsetEntry 52, 6
	LearnsetEntry 88, 8
	LearnsetEntry 106, 13
	LearnsetEntry 510, 15
	LearnsetEntry 499, 20
	LearnsetEntry 246, 22
	LearnsetEntry 481, 27
	LearnsetEntry 157, 29
	LearnsetEntry 436, 34
	LearnsetEntry 133, 36
	LearnsetEntry 34, 41
	LearnsetEntry 105, 43
	LearnsetEntry 53, 48
	LearnsetEntry 414, 50
	LearnsetEntry 65535, 65535
