Species_453:
	LearnsetEntry 310, 1
	LearnsetEntry 189, 3
	LearnsetEntry 40, 8
	LearnsetEntry 269, 10
	LearnsetEntry 228, 15
	LearnsetEntry 185, 17
	LearnsetEntry 279, 22
	LearnsetEntry 207, 24
	LearnsetEntry 426, 29
	LearnsetEntry 389, 31
	LearnsetEntry 474, 36
	LearnsetEntry 417, 38
	LearnsetEntry 398, 43
	LearnsetEntry 188, 45
	LearnsetEntry 562, 47
	LearnsetEntry 260, 50
	LearnsetEntry 65535, 65535
