Species_548:
	LearnsetEntry 71, 1
	LearnsetEntry 74, 4
	LearnsetEntry 73, 8
	LearnsetEntry 79, 10
	LearnsetEntry 72, 13
	LearnsetEntry 235, 17
	LearnsetEntry 345, 19
	LearnsetEntry 78, 22
	LearnsetEntry 202, 26
	LearnsetEntry 312, 28
	LearnsetEntry 270, 31
	LearnsetEntry 412, 35
	LearnsetEntry 494, 37
	LearnsetEntry 241, 40
	LearnsetEntry 495, 44
	LearnsetEntry 437, 46
	LearnsetEntry 65535, 65535
