Species_629:
	LearnsetEntry 16, 1
	LearnsetEntry 43, 1
	LearnsetEntry 31, 5
	LearnsetEntry 365, 10
	LearnsetEntry 417, 14
	LearnsetEntry 260, 19
	LearnsetEntry 185, 23
	LearnsetEntry 386, 28
	LearnsetEntry 432, 32
	LearnsetEntry 366, 37
	LearnsetEntry 403, 41
	LearnsetEntry 399, 46
	LearnsetEntry 373, 50
	LearnsetEntry 18, 55
	LearnsetEntry 413, 59
	LearnsetEntry 119, 64
	LearnsetEntry 65535, 65535
