Species_215:
	LearnsetEntry 10, 1
	LearnsetEntry 43, 1
	LearnsetEntry 269, 1
	LearnsetEntry 98, 8
	LearnsetEntry 185, 10
	LearnsetEntry 196, 14
	LearnsetEntry 154, 16
	LearnsetEntry 97, 20
	LearnsetEntry 232, 22
	LearnsetEntry 468, 25
	LearnsetEntry 251, 28
	LearnsetEntry 103, 32
	LearnsetEntry 163, 35
	LearnsetEntry 289, 40
	LearnsetEntry 386, 44
	LearnsetEntry 420, 47
	LearnsetEntry 65535, 65535
