Species_353:
	LearnsetEntry 282, 1
	LearnsetEntry 103, 4
	LearnsetEntry 101, 7
	LearnsetEntry 180, 10
	LearnsetEntry 425, 13
	LearnsetEntry 261, 16
	LearnsetEntry 185, 19
	LearnsetEntry 506, 22
	LearnsetEntry 174, 26
	LearnsetEntry 247, 30
	LearnsetEntry 373, 34
	LearnsetEntry 389, 38
	LearnsetEntry 289, 42
	LearnsetEntry 288, 46
	LearnsetEntry 271, 50
	LearnsetEntry 566, 54
	LearnsetEntry 65535, 65535
