Species_723:
	LearnsetEntry 43, 1
	LearnsetEntry 35, 1
	LearnsetEntry 101, 7
	LearnsetEntry 100, 13
	LearnsetEntry 282, 19
	LearnsetEntry 191, 25
	LearnsetEntry 94, 31
	LearnsetEntry 289, 37
	LearnsetEntry 375, 43
	LearnsetEntry 428, 49
	LearnsetEntry 334, 55
	LearnsetEntry 133, 55
	LearnsetEntry 105, 61
	LearnsetEntry 354, 67
	LearnsetEntry 68, 73
	LearnsetEntry 243, 73
	LearnsetEntry 65535, 65535
