Species_227:
	LearnsetEntry 43, 1
	LearnsetEntry 64, 1
	LearnsetEntry 28, 6
	LearnsetEntry 232, 9
	LearnsetEntry 314, 12
	LearnsetEntry 31, 17
	LearnsetEntry 364, 20
	LearnsetEntry 129, 23
	LearnsetEntry 191, 28
	LearnsetEntry 97, 31
	LearnsetEntry 211, 34
	LearnsetEntry 163, 39
	LearnsetEntry 319, 42
	LearnsetEntry 403, 45
	LearnsetEntry 475, 50
	LearnsetEntry 400, 53
	LearnsetEntry 65535, 65535
